name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish production package
        run: cd prod && npx jsr publish

      - name: Publish insiders package
        run: cd insiders && npx jsr publish
