name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.9
        with:
          version: latest
      
      # - name: Install Packages
      #   run: pnpm install

      - name: Publish production package
        working-directory: prod
        run: deno publish --unstable-bare-node-builtins --unstable-sloppy-imports --unstable-byonm --no-check

      - name: Publish insiders package
        working-directory: insiders
        run: deno publish --unstable-bare-node-builtins --unstable-sloppy-imports --unstable-byonm --no-check